# Generated by Django 4.2 on 2023-04-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voices',
            new_name='votes',
        ),
    ]
